### ISSUE TITLE
[Bug]: Build.sh fails on Ubuntu MATE

### ISSUE THREAD

**Issue by netsmile** [ethical-haquer/Galaxy-Flasher#19]
### What happened?

Downloading sources
Downloading https://files.pythonhosted.org/packages/1c/41/91955188e97c7b85fbaac6bbf4e33de028899e0aa31bdce99b1afe2eeb17/pycairo-1.26.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  338k  100  338k    0     0  1053k      0 --:--:-- --:--:-- --:--:-- 1051k
Downloading https://files.pythonhosted.org/packages/f9/9e/6bab1ed3bd878f0912d9a0600c21f3d88bab0e8a8d4c3ce50f5cf336faaf/pygobject-3.48.2.tar.gz
100  698k  100  698k    0     0  4771k      0 --:--:-- --:--:-- --:--:-- 4771k
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /home/csaba/Desktop/TABLET FIX/sm-t560 custom rom/Tools/galaxy-flasher-v0.5.1-alpha-linux/flatpak/.flatpak-builder/git/https_gitlab.gnome.org_GNOME_vte.git_-PH9ET2/
Fetching git repo https://gitlab.gnome.org/GNOME/vte.git/, ref refs/heads/master
remote: Enumerating objects: 374, done.
remote: Counting objects: 100% (374/374), done.
remote: Compressing objects: 100% (326/326), done.
remote: Total 374 (delta 90), reused 196 (delta 43), pack-reused 0 (from 0)
Receiving objects: 100% (374/374), 986.69 KiB | 1.40 MiB/s, done.
Resolving deltas: 100% (90/90), done.
From https://gitlab.gnome.org/GNOME/vte
 * [new branch]      master     -> master
Initializing build dir
Committing stage init to cache
Starting build of com.ethicalhaquer.galaxyflasher
========================================================================
Building module python3-PyGObject in /home/csaba/Desktop/TABLET FIX/sm-t560 custom rom/Tools/galaxy-flasher-v0.5.1-alpha-linux/flatpak/.flatpak-builder/build/python3-PyGObject-1
========================================================================
Running: pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} "PyGObject" --no-build-isolation
Using pip 24.1.2 from /usr/lib/python3.11/site-packages/pip (python 3.11)
Looking in links: file:///run/build/python3-PyGObject
Requirement already satisfied: PyGObject in /usr/lib/python3.11/site-packages (3.48.2)
Committing stage build-python3-PyGObject to cache
========================================================================
Building module Galaxy-Flasher in /home/csaba/Desktop/TABLET FIX/sm-t560 custom rom/Tools/galaxy-flasher-v0.5.1-alpha-linux/flatpak/.flatpak-builder/build/Galaxy-Flasher-1
========================================================================
Running: pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: PyGObject in /usr/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (3.48.2)
Running: cp -r locales /app/locales/
Running: cp -r odin4-wrapper.sh /app/odin4-wrapper.sh
Running: install -D galaxy-flasher.py /app/galaxy-flasher
Running: install -D entry.sh /app/bin/entry
Running: install -D galaxy-flasher.desktop /app/share/applications/com.ethicalhaquer.galaxyflasher.desktop
Committing stage build-Galaxy-Flasher to cache
========================================================================
Building module vte in /home/csaba/Desktop/TABLET FIX/sm-t560 custom rom/Tools/galaxy-flasher-v0.5.1-alpha-linux/flatpak/.flatpak-builder/build/vte-1
========================================================================
Already on 'master'
The Meson build system
Version: 1.3.2
Source dir: /run/build/vte
Build dir: /run/build/vte/_flatpak_build
Build type: native build
Project name: vte
Project version: 0.79.0
C compiler for the host machine: ccache cc (gcc 13.2.0 "cc (GCC) 13.2.0")
C linker for the host machine: cc ld.bfd 2.42
C++ compiler for the host machine: ccache c++ (gcc 13.2.0 "c++ (GCC) 13.2.0")
C++ linker for the host machine: c++ ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -std=gnu11: YES 
../meson.build:148: WARNING: Consider using the built-in option for language standard version instead of using "-std=gnu11".
Compiler for C++ supports arguments -std=gnu++20: YES 
../meson.build:156: WARNING: Consider using the built-in option for language standard version instead of using "-std=gnu++20".
Program python3 (dataclasses) found: YES (/usr/bin/python) modules: dataclasses
Header "sys/ioctl.h" has symbol "TIOCGWINSZ" : YES 
Library m found: YES
Checking if "fork" compiles: YES 
Checking if "grantpt" compiles: YES 
Checking if "posix_openpt" compiles: YES 
Checking if "ptsname" compiles: YES 
Checking if "tcgetattr" compiles: YES 
Checking if "unlockpt" compiles: YES 
Checking if "explicit_bzero" compiles: YES 
Checking if "fdwalk" compiles: NO 
Checking if "pread" compiles: YES 
Checking if "pwrite" compiles: YES 
Checking if "strchrnul" compiles: YES 
Checking if "close_range" compiles: YES 
Checking if "ceil" with dependency -lm compiles: YES 
Checking if "floor" with dependency -lm compiles: YES 
Checking if "round" with dependency -lm compiles: YES 
Compiler for C supports arguments -Wall: YES 
Compiler for C supports arguments -Wextra: YES 
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wcast-function-type: YES 
Compiler for C supports arguments -Wclobbered: YES 
Compiler for C supports arguments -Wempty-body: YES 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Werror=init-self: YES 
Compiler for C supports arguments -Werror=missing-include-dirs: YES 
Compiler for C supports arguments -Werror=pointer-arith: YES 
Compiler for C supports arguments -Wfloat-equal: YES 
Compiler for C supports arguments -Wignored-qualifiers: YES 
Compiler for C supports arguments -Winvalid-pch: YES 
Compiler for C supports arguments -Wlogical-op: YES 
Compiler for C supports arguments -Wmisleading-indentation: YES 
Compiler for C supports arguments -Wmissing-declarations: YES 
Compiler for C supports arguments -Wmissing-field-initializers: YES 
Compiler for C supports arguments -Wmissing-format-attribute: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wmissing-noreturn: YES 
Compiler for C supports arguments -Wno-deprecated-declarations: YES 
Compiler for C supports arguments -Wno-address-of-packed-member: YES 
Compiler for C supports arguments -Wno-c99-designator: NO 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-packed: YES 
Compiler for C supports arguments -Wno-switch-enum: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wno-volatile: NO 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wshift-negative-value: YES 
Compiler for C supports arguments -Wsign-compare: YES 
Compiler for C supports arguments -Wstrict-aliasing=2: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wuninitialized: YES 
Compiler for C supports arguments -Wuninitialized: YES (cached)
Compiler for C supports arguments -Wunsafe-loop-optimizations: YES 
Compiler for C supports arguments -Wunused: YES 
Compiler for C supports arguments -Wunused-but-set-parameter: YES 
Compiler for C supports arguments -Wunused-but-set-variable: YES 
Compiler for C supports arguments -Wunused-function: YES 
Compiler for C supports arguments -Wunused-label: YES 
Compiler for C supports arguments -Wunused-local-typedefs: YES 
Compiler for C supports arguments -Wunused-value: YES 
Compiler for C supports arguments -Wunused-variable: YES 
Compiler for C supports arguments -Wvla: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
Compiler for C supports arguments -fdiagnostics-show-option: YES 
Compiler for C supports arguments -fno-common: YES 
Compiler for C supports arguments -fno-semantic-interposition: YES 
Compiler for C supports arguments -fno-strict-aliasing: YES 
Compiler for C supports arguments -Waggregate-return: YES 
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Werror=missing-prototypes: YES 
Compiler for C supports arguments -Wimplicit: YES 
Compiler for C supports arguments -Wimplicit-fallthrough=3: YES 
Compiler for C supports arguments -Wmissing-parameter-type: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wold-style-declaration: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Woverride-init: YES 
Compiler for C supports arguments -Wsign-compare: YES (cached)
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C++ supports arguments -Wall: YES 
Compiler for C++ supports arguments -Wextra: YES 
Compiler for C++ supports arguments -Wcast-align: YES 
Compiler for C++ supports arguments -Wcast-function-type: YES 
Compiler for C++ supports arguments -Wclobbered: YES 
Compiler for C++ supports arguments -Wempty-body: YES 
Compiler for C++ supports arguments -Wendif-labels: YES 
Compiler for C++ supports arguments -Werror=init-self: YES 
Compiler for C++ supports arguments -Werror=missing-include-dirs: YES 
Compiler for C++ supports arguments -Werror=pointer-arith: YES 
Compiler for C++ supports arguments -Wfloat-equal: YES 
Compiler for C++ supports arguments -Wignored-qualifiers: YES 
Compiler for C++ supports arguments -Winvalid-pch: YES 
Compiler for C++ supports arguments -Wlogical-op: YES 
Compiler for C++ supports arguments -Wmisleading-indentation: YES 
Compiler for C++ supports arguments -Wmissing-declarations: YES 
Compiler for C++ supports arguments -Wmissing-field-initializers: YES 
Compiler for C++ supports arguments -Wmissing-format-attribute: YES 
Compiler for C++ supports arguments -Wmissing-include-dirs: YES 
Compiler for C++ supports arguments -Wmissing-noreturn: YES 
Compiler for C++ supports arguments -Wno-deprecated-declarations: YES 
Compiler for C++ supports arguments -Wno-address-of-packed-member: YES 
Compiler for C++ supports arguments -Wno-c99-designator: NO 
Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
Compiler for C++ supports arguments -Wno-packed: YES 
Compiler for C++ supports arguments -Wno-switch-enum: YES 
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-volatile: YES 
Compiler for C++ supports arguments -Wshadow: YES 
Compiler for C++ supports arguments -Wshift-negative-value: YES 
Compiler for C++ supports arguments -Wsign-compare: YES 
Compiler for C++ supports arguments -Wstrict-aliasing=2: YES 
Compiler for C++ supports arguments -Wtype-limits: YES 
Compiler for C++ supports arguments -Wundef: YES 
Compiler for C++ supports arguments -Wuninitialized: YES 
Compiler for C++ supports arguments -Wuninitialized: YES (cached)
Compiler for C++ supports arguments -Wunsafe-loop-optimizations: YES 
Compiler for C++ supports arguments -Wunused: YES 
Compiler for C++ supports arguments -Wunused-but-set-parameter: YES 
Compiler for C++ supports arguments -Wunused-but-set-variable: YES 
Compiler for C++ supports arguments -Wunused-function: YES 
Compiler for C++ supports arguments -Wunused-label: YES 
Compiler for C++ supports arguments -Wunused-local-typedefs: YES 
Compiler for C++ supports arguments -Wunused-value: YES 
Compiler for C++ supports arguments -Wunused-variable: YES 
Compiler for C++ supports arguments -Wvla: YES 
Compiler for C++ supports arguments -Wwrite-strings: YES 
Compiler for C++ supports arguments -fdiagnostics-show-option: YES 
Compiler for C++ supports arguments -fno-common: YES 
Compiler for C++ supports arguments -fno-semantic-interposition: YES 
Compiler for C++ supports arguments -fno-strict-aliasing: YES 
Compiler for C++ supports arguments -Wimplicit-fallthrough=5: YES 
Compiler for C++ supports arguments -Wnon-virtual-dtor: YES 
Compiler for C++ supports arguments -Wstrict-null-sentinel: YES 
Compiler for C++ supports arguments -fvisibility-inlines-hidden: YES 
Compiler for C++ supports arguments -fvisibility=hidden: YES 
Compiler for C++ supports arguments -fvisibility-inlines-hidden: YES (cached)
Compiler for C++ supports arguments -fvisibility=hidden: YES (cached)
Compiler for C supports arguments -Werror=format=2 -Werror=format-nonliteral -Werror=format-security: YES 
Compiler for C++ supports arguments -Werror=format=2 -Werror=format-nonliteral -Werror=format-security: YES 
../meson.build:588: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
../meson.build:588: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
../meson.build:589: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
../meson.build:589: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
Compiler for C supports link arguments -Wl,-Bsymbolic: YES 
Compiler for C++ supports link arguments -Wl,-Bsymbolic: YES 
Compiler for C supports link arguments -Wl,-Bsymbolic-functions: YES 
Compiler for C++ supports link arguments -Wl,-Bsymbolic-functions: YES 
Compiler for C supports link arguments -fstack-protector: YES 
Compiler for C++ supports link arguments -fstack-protector: YES 
Compiler for C supports link arguments -fstack-protector-strong: YES 
Compiler for C++ supports link arguments -fstack-protector-strong: YES 
Found pkg-config: YES (/usr/bin/pkg-config) 2.2.0
Run-time dependency cairo found: YES 1.18.0
Run-time dependency cairo-gobject found: YES 1.18.0
Run-time dependency gio-2.0 found: YES 2.80.4
Run-time dependency glib-2.0 found: YES 2.80.4
Run-time dependency gobject-2.0 found: YES 2.80.4
Run-time dependency pango found: YES 1.52.2
Run-time dependency libpcre2-8 found: YES 10.42
Run-time dependency threads found: YES
Run-time dependency liblz4 found: YES 1.9.4
Run-time dependency fribidi found: YES 1.0.15
Run-time dependency gnutls found: YES 3.8.0
Run-time dependency gtk4 found: YES 4.14.4
Run-time dependency icu-uc found: YES 73.2
Run-time dependency libsystemd found: YES 254
Configuring config.h using configuration
Configuring vteversion.h using configuration
Program glib-mkenums found: YES (/usr/bin/glib-mkenums)
Dependency gio-2.0 found: YES 2.80.4 (cached)
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Dependency glib-2.0 found: YES 2.80.4 (cached)
Program /usr/bin/glib-genmarshal found: YES (/usr/bin/glib-genmarshal)
Dependency gio-2.0 found: YES 2.80.4 (cached)
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Configuring vte.csh using configuration
Configuring vte.sh using configuration
Dependency gio-2.0 found: YES 2.80.4 (cached)
Program /usr/bin/glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Run-time dependency gobject-introspection-1.0 found: YES 1.80.1
Dependency gobject-introspection-1.0 found: YES 1.80.1 (cached)
Dependency gobject-introspection-1.0 found: YES 1.80.1 (cached)
Program /usr/bin/g-ir-scanner found: YES (/usr/bin/g-ir-scanner)
Dependency gobject-introspection-1.0 found: YES 1.80.1 (cached)
Program /usr/bin/g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
../bindings/vala/meson.build:19: WARNING: add_languages is missing native:, assuming languages are wanted for both host and build.
Vala compiler for the host machine: valac (valac 0.56.17)
Library posix found: YES
Program vapigen found: YES (/usr/bin/vapigen)
Program msgfmt found: YES (/usr/bin/msgfmt)
Program msginit found: YES (/usr/bin/msginit)
Program msgmerge found: YES (/usr/bin/msgmerge)
Program xgettext found: YES (/usr/bin/xgettext)
Program meson_changelog.sh found: YES (/run/build/vte/meson_changelog.sh)
Configuring Makefile using configuration
Configuring .gitignore with command
Message: 
Configuration for VTE:

  Version:      0.79.0

  C compiler:   gcc (version 13.2.0)
  C++ compiler: gcc (version 13.2.0)

  Coverage:     false
  Debug:        false

  A11y:         true
  Docs:         false
  FRIBIDI:      true
  GNUTLS:       true
  GTK+ 3.0:     false
  GTK+ 4.0:     true
  ICU:          true
  GIR:          true
  systemd:      true
  SIXEL:        false
  Glade:        true
  Vala:         true

  Prefix:       /app

../meson.build:749: WARNING: This is an unstable development release!

Build targets in project: 141

vte 0.79.0

  User defined options
    libdir: /app/lib
    prefix: /app
    gtk3  : false
    gtk4  : true

Found ninja-1.11.1 at /usr/bin/ninja
[1/234] Generating src/minifont-coverage.inc with a custom command
FAILED: src/minifont-coverage.inc 
/run/build/vte/src/minifont-coverage.py --output src/minifont-coverage.inc ../src/minifont.cc
/bin/sh: line 1: /run/build/vte/src/minifont-coverage.py: cannot execute: required file not found
[4/234] Generating src/modes with a custom command
ninja: build stopped: subcommand failed.
Error: module vte: Child process exited with code 1

### Galaxy Flasher version

Alpha v0.5.1

**Comment by ethical-haquer** [comment]
Vte is not a dependency anymore in v0.6.0.
